defaults:
  # - mppi: albert
  - isaacgym: panda

env_type: panda_env
# n_steps: 10000
# actors: ['albert', 'goal']
# initial_actor_positions: [[0.0, 0.0, 0.05]]
# nx: 18

# hydra:
#   searchpath:
#     - pkg://params