defaults:
  - mppi: point
  - isaacgym: point

env_type: point_env
task: push
goal: [-3.75, -3.75]

# n_steps: 10000
# actors: ['albert', 'goal']
# initial_actor_positions: [[0.0, 0.0, 0.05]]
kp_suction: 400
suction_active: True
multi_modal: False
cube_on_shelf: False

# hydra:
#   searchpath:
#     - pkg://params