defaults:
  - mppi: panda
  - isaacgym: panda

env_type: panda_env
task: reactive_pick

# n_steps: 10000
# actors: ['albert', 'goal']
# initial_actor_positions: [[0.0, 0.0, 0.05]]
nx: 18
kp_suction: 400
suction_active: False

# hydra:
#   searchpath:
#     - pkg://params