defaults:
  - mppi: base_mppi
  - isaacgym: point

env_type: point_env
task: push
goal: [-3.75, -3.75]

# n_steps: 10000
# actors: ['albert', 'goal']
# initial_actor_positions: [[0.0, 0.0, 0.05]]
nx: 18

# hydra:
#   searchpath:
#     - pkg://params